project:
  type: website
  output-dir: docs 
  resources:
    - CNAME  # <-- Bu satır, dosyanın yayınlanan klasöre gitmesini garanti eder.
  
website:
  title: "Pilevneli"            # change to your site title
  site-url: "https://pilevneli.github.io/vault/" # Google SEO için bu satır ŞARTTIR
  description: "Veri Bilimi Portfolyosu ve Blog Yazıları" 

  navbar:
    background: primary
    search: true 
    # Navbar 'üstte' yatay bir şerittir.
    # 'left' altındaki linkler, şeridin soluna dizilir.
    left: 
      - href: index.qmd
        text: Ana Sayfa
      - href: about.qmd
        text: Hakkımda
    # 'right' altındakiler şeridin sağına dizilir (Genelde ikonlar buraya konur).
    right:
      - icon: github
        href: https://github.com/pilevneli
      - icon: linkedin
        href: https://www.linkedin.com/in/tolga-pilevneli/
      - icon: mortarboard-fill
        href: https://avesis.ankara.edu.tr/tpilevneli

format:
  html:
    theme: cosmo
    css: styles.css
    include-after-body: js-scripts.html
    toc: true
    
editor: visual

